package POJOs;
// Generated 03-nov-2024 13:59:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Boolean estado;
     private String usuario;
     private String contrasenia;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Usuario() {
    }

    public Usuario(Boolean estado, String usuario, String contrasenia, Set<Cliente> clientes, Set<Empleado> empleados, Set<Persona> personas) {
       this.estado = estado;
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.clientes = clientes;
       this.empleados = empleados;
       this.personas = personas;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


